# Generated by Django 4.2.1 on 2023-06-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=255)),
                ('fila', models.TextField(max_length=255)),
                ('asiento', models.TextField(max_length=255)),
            ],
        ),
    ]
